output "ec2_public_ip" {
  description = "Public IP of EC2 instance"
  value       = aws_instance.app.public_ip
}

output "ec2_private_ip" {
  description = "Private IP of EC2 instance"
  value       = aws_instance.app.private_ip
}

output "ec2_instance_id" {
  description = "ID of EC2 instance"
  value       = aws_instance.app.id
}
