      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init (local)
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate
